In [1]:
from katsu.polarimetry import full_mueller_polarimetry,broadcasted_full_mueller_polarimetry,broadcast_kron,broadcast_outer
from katsu.mueller import linear_polarizer,linear_retarder
import numpy as np

In [3]:

# Mout = broadcasted_full_mueller_polarimetry(thetas,Min=Min)

In [54]:
starting_angles={'psg_polarizer':0,
                'psg_qwp':0,
                'psa_qwp':0,
                'psa_polarizer':0}
nmeas = 26
thetas = np.linspace(0,2*np.pi,nmeas)

Min = linear_polarizer(np.random.random()) @ linear_retarder(np.random.random(),np.random.random())

Mg = linear_retarder(starting_angles['psg_qwp']+thetas,np.pi/2) @ linear_polarizer(starting_angles['psg_polarizer'])
Ma = linear_polarizer(starting_angles['psa_polarizer']) @ linear_retarder(starting_angles['psa_qwp']+thetas*5,np.pi/2)
PSA = Ma[...,0,:]
# PSA = PSA[...,np.newaxis]

PSG = Mg[...,:,0]
power = 1
# PSG = PSG[...,np.newaxis]
Wmat = broadcast_outer(PSA,PSG).reshape([nmeas,16])
PSG = PSG[...,np.newaxis]
PSA = PSA[...,np.newaxis]
Min = np.broadcast_to(Min,[*PSA.shape[:-2],4,4])

Pmat = (np.swapaxes(PSA,-1,-2) @ Min @ PSG) * power
M_meas = np.linalg.pinv(Wmat) @ Pmat[...,0,0]

In [55]:
print(Min[0])
print(M_meas.reshape([4,4]))

[[ 0.5         0.40017042  0.27793622 -0.11231694]
 [ 0.42169297  0.33749811  0.2344075  -0.09472653]
 [ 0.26865412  0.21501486  0.14933742 -0.06034882]
 [ 0.          0.          0.          0.        ]]
[[ 5.00000000e-01  4.00170416e-01  2.77936220e-01 -1.12316944e-01]
 [ 4.21692973e-01  3.37498105e-01  2.34407502e-01 -9.47265317e-02]
 [ 2.68654120e-01  2.15014862e-01  1.49337421e-01 -6.03488193e-02]
 [ 1.66533454e-16 -2.49800181e-16 -2.35922393e-16  1.38777878e-17]]


In [ ]:
Wmat.shape

(16, 4, 4)